using UnityEngine.InputSystem;
using UnityEngine.Events;
using UnityEngine;

[CreateAssetMenu(fileName = "InputReader", menuName = "Project/Input/Input Reader")]
public class InputReaderSO : ScriptableObject, InputActions.IPlayerActions, InputActions.IUIActions, IInitializable, IGameService
{
    private InputActions _inputActions;

    // Values that states can read (Polling)
    public InputActions InputActions => _inputActions;
    public Vector2 MoveValue { get; private set; }

    // Events for specific actions (Observer)
    public event UnityAction<Vector2> MoveEvent;
    public event UnityAction InteractEvent;
    public event UnityAction InventoryRequest;

    public void Initialize()
    {
        if (_inputActions == null)
        {
            _inputActions = new InputActions();
            _inputActions.Player.SetCallbacks(this);
            _inputActions.UI.SetCallbacks(this);
        }
    }

    public void enablePlayerInputs() => _inputActions.Player.Enable();
    public void DisablePlayerInputs() => _inputActions.Player.Disable();

    public void SwitchToPlayerInput()
    {
        _inputActions.UI.Disable();
        _inputActions.Player.Enable();
    }

    public void SwitchToUIInput()
    {
        _inputActions.Player.Disable();
        _inputActions.UI.Enable();
    }

    // Methods of the interface generated by Unity
    public void OnMove(InputAction.CallbackContext context)
    {
        MoveValue = context.ReadValue<Vector2>();
        MoveEvent?.Invoke(MoveValue);
    }

    public void OnInteract(InputAction.CallbackContext context)
    {
        if (context.performed) InteractEvent?.Invoke();
    }
    public void OnInventoryRequest(InputAction.CallbackContext context)
    {
        if (context.performed) InventoryRequest?.Invoke();
    }

    public void OnAttack(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnPrevious(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnNext(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnNavigate(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnSubmit(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnCancel(InputAction.CallbackContext context)
    {
        ///throw new System.NotImplementedException();
    }

    public void OnPoint(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnClick(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnRightClick(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnMiddleClick(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnScrollWheel(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnTrackedDevicePosition(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnTrackedDeviceOrientation(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }
}