using UnityEngine.InputSystem;
using UnityEngine.Events;
using UnityEngine;

[CreateAssetMenu(fileName = "InputReader", menuName = "Project/Input/Input Reader")]
public class InputReaderSO : ScriptableObject, InputActions.IPlayerActions, IInitializable, IGameService
{
    private InputActions _inputActions;

    // Values that states can read (Polling)
    public Vector2 MoveValue { get; private set; }

    // Events for specific actions (Observer)
    public event UnityAction<Vector2> MoveEvent;
    public event UnityAction InteractEvent;
    public event UnityAction OpenInventoryEvent;

    public void Initialize()
    {
        if (_inputActions == null)
        {
            _inputActions = new InputActions();
            _inputActions.Player.SetCallbacks(this);
        }
    }

    public void EnablePlayerInput()
    {
        _inputActions.UI.Disable();
        _inputActions.Player.Enable();
    }

    public void EnableUIInput()
    {
        _inputActions.Player.Disable();
        _inputActions.UI.Enable();
    }

    // Methods of the interface generated by Unity
    public void OnMove(InputAction.CallbackContext context)
    {
        MoveValue = context.ReadValue<Vector2>();
        MoveEvent?.Invoke(MoveValue);
    }

    public void OnInteract(InputAction.CallbackContext context)
    {
        if (context.phase == InputActionPhase.Performed)
            InteractEvent?.Invoke();
    }

    //public void OnOpenInventory(InputAction.CallbackContext context)
    //{
    //    if (context.phase == InputActionPhase.Performed)
    //        OpenInventoryEvent?.Invoke();
    //}

    public void OnAttack(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnPrevious(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }

    public void OnNext(InputAction.CallbackContext context)
    {
        //throw new System.NotImplementedException();
    }
}